server:
  port: 8781


#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#指定sever名称
spring:
  application:
    name: order-service

#定义负载均衡略为随机，默认轮询
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#修改调用超时时间 单位为秒
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 11000